LEDs:
    delta_z: 8.0                       
    LED_mode: single 
    multi_mode: ~

---
system:
  dz: 125
  focus_slice: 60                  
  oNA: 0.95                         
  spsize: 3.76                     
  Mag: 40.                         

---
dataset:
  path_dir: 'bio_dataset'              
  name_head: U2OS_cell.tif         
  recon_frames: ~         

---
recon:
  mod: 'transmission'                      
  forward_mod: 'Multi_Born'         
  grad: 'dwt'   

  orig_size: [250, 250]              
  cut_index: [25, 25]                           
  imsize: 200                     
  stack_num: 65                                    
  pad: 20                             

  save_path: 'Bio_sample_exp' 
  post_suffix: ''

